Feature/text text 컴포넌트
FAST-gamsungcoding/FE_MiniProject pull request #14
Opened 2023-11-24 03:35 UTC by kyungkyuBae

### ⛳️ Task

- [ ] 마진 제거
- [ ] default값 수정
- [ ] 폰트 적용 

### ✍️ Note

### ⚡️ Test

### 📸 Screenshot

### 📎 Reference

2023-11-24 04:53 UTC, junkue20 approved these changes
`/text/index.tsx` 부분 수정된 것 확인했습니다! 감사해요~~

2023-11-24 09:01 UTC, gahyuun requested changes
경규님 pull 안받으셨나요? stories 지웠던 게 다시 파일에 존재하네요ㅠㅠㅠ 이 부분 지우고 리뷰 request 해주세요

2023-11-25 11:52 UTC, gahyuun commented on src/components/text/text.scss
> +
준규님 프리텐다드 설정하셔서 이 부분은 지워주세용

2023-11-25 11:52 UTC, gahyuun commented on src/stories/Button.stories.ts
stories 파일 지워주실 수 있나요?? 계속 이 브랜치에 develop 반영이 안되는데 일단 지우고 머지하는 방향으로 하는 게 좋을 것 같아용

2023-11-25 12:15 UTC, gahyuun approved these changes

2023-11-25 12:16 UTC, merged