Feature/detail page 상세페이지 구현
FAST-gamsungcoding/FE_MiniProject pull request #30
Opened 2023-11-26 18:01 UTC by kyungkyuBae

### ⛳️ Task

- [x] 상세페이지 구현
### ✍️ Note
### ⚡️ Test
### 📸 Screenshot
<img width="1399" alt="image" src="https://github.com/FAST-gamsungcoding/FE_MiniProject/assets/131759810/abe99528-3f29-4e32-8aa4-b9db0db52d5c">

### 📎 Reference

2023-11-26 18:06 UTC, syb0127 approved these changes
상세페이지 퍼블리싱 작업 까다로우셨을텐데 고생 많으셨습니다!

2023-11-26 18:17 UTC, gahyuun approved these changes
경규님 늦은 시간까지 너무 고생하셨어요! 
지금 file change에 준규님이랑 제 파일이 올라와있던데 이 부분 꼬인건지 확인 부탁드려요..!😂

2023-11-26 18:17 UTC, gahyuun commented on src/app/(header)/rooms/[id]/(component)/carousel/carousel.tsx
> +  const next = useCallback(() => slickRef.current?.slickNext(), []);
previous와 next를 useCallback으로 감싼 이유가 궁금합니다!

2023-11-26 18:17 UTC, gahyuun commented on src/app/(header)/rooms/[id]/(component)/custom-calendar/customCalendar.tsx
> +}
저희 interface아닌 type을 우선적으로 사용하기로 했고 type 무조건 파일 분리하기로 정했습니다 이 부분 수정 부탁드려용! 그리고 Props도 필요시가 아니면 작성하지 않기로 정했습니당..

2023-11-26 18:17 UTC, gahyuun commented on src/app/(header)/rooms/[id]/(component)/detail-description/detailDescription.module.scss
> +.adress {
address 오타일까용?

2023-11-26 18:17 UTC, gahyuun commented on src/app/(header)/rooms/[id]/(component)/detail-description/detailDescription.module.scss
> +.DetailDescription {
저는 클래스명 카멜케이스 생각했는데 파스칼 케이스 사용하셨네용! 이 부분 내일 한 번 다 같이 얘기해볼까요?!

2023-11-26 18:17 UTC, gahyuun commented on src/app/(header)/rooms/[id]/(component)/detail-description/detailDescription.tsx
> +function DetailDescription({ adress, desc }: { adress: string; desc: string }) {
저희 layout 에서 {children}:{children:React.ReactNode} 이 props가 아닌 이상 파일로 분리하기로 해서 이 부분도 수정 부탁드릴게요!

2023-11-26 18:17 UTC, gahyuun commented on src/app/(header)/rooms/[id]/(component)/detail-page/detailPage.tsx
> +  return res.data;
저희 axios를 instance로 분리해야 할 것 같은데 이 부분 내일 같이 정하면 좋을 것 같아욥

2023-11-26 18:17 UTC, gahyuun commented on src/app/(header)/rooms/[id]/.gitkeep
gitkeep 은 삭제 부탁드려요ㅠ

2023-11-26 18:17 UTC, gahyuun commented on src/app/(header)/rooms/[id]/page.tsx
저희 함수 선언식 사용하기로 했었는데 화살표 함수를 사용하신 이유가 있을까요??

2023-11-26 18:17 UTC, gahyuun commented on src/app/cart/layout.tsx
cart가 왜 새로 만드신 파일로 pr에 올라가있는지 여쭤봐도 될까요?!

2023-11-26 18:17 UTC, gahyuun commented on src/app/(header)/rooms/[id]/(component)/carousel/carousel.module.scss
경규님 지금  (component) 폴더로 되어있더라구요 저희 _components로 사용하기로 했던 거 기억하시나요!? (component)로 사용하게 되면 하위 폴더도 라우팅이 되어서 _를 사용하셔야해요!
 그리구 폴더 파일명을 indext.tsx로 적지 않으셨던데 ( ex carousel 폴더에 index.tsx가 아닌 carousel.tsx) 저희 import 문을 조금이라도 짧게 하기 위해 index.tsx 사용하기로 하지 않았나요..!?

2023-11-26 18:19 UTC, gahyuun requested changes
저희 제목 변경해주시구, 패키지 설치한 거 있으시면 pr 올릴 때 npm i 하라구 말씀해주세요..! request changes는 깃허브 꼬인건지만 확인 한번만 해주시면 바로 approve로 변경할게요..!! 😂😂😂

2023-11-27 05:11 UTC, kyungkyuBae commented on src/app/(header)/rooms/[id]/(component)/custom-calendar/customCalendar.tsx
> +}
회의하기 전에 작업한 내용이라 최대한 수정한다고 하긴했는데 남아있었네유.. 수정하겠습니다

2023-11-27 05:15 UTC, kyungkyuBae commented on src/app/(header)/rooms/[id]/(component)/detail-description/detailDescription.module.scss
> +.adress {
오타였습니다 수정하겠습니다!

2023-11-27 05:16 UTC, kyungkyuBae commented on src/app/(header)/rooms/[id]/(component)/detail-description/detailDescription.module.scss
> +.DetailDescription {
이 클래스만 제가 파스칼로 사용한거같습니다 다른 클래스는 카멜케이스 사용해서 이부분도 수정하겠습니다

2023-11-27 05:17 UTC, kyungkyuBae commented on src/app/(header)/rooms/[id]/(component)/detail-description/detailDescription.tsx
> +function DetailDescription({ adress, desc }: { adress: string; desc: string }) {
타입 파일로 분리 수정하겠습니다

2023-11-27 05:19 UTC, kyungkyuBae commented on src/app/(header)/rooms/[id]/page.tsx
수정했습니다!

2023-11-27 05:20 UTC, kyungkyuBae commented on src/app/(header)/rooms/[id]/(component)/carousel/carousel.module.scss
폴더명이랑 파일명 둘다 수정하겠습니다

2023-11-27 11:30 UTC, gahyuun commented on src/app/cart/layout.tsx
앗 상관 없을 것 같아요..!!

2023-11-27 11:32 UTC, gahyuun approved these changes
고생하셨습니다~!

2023-11-27 11:39 UTC, syb0127 approved these changes

2023-11-27 13:00 UTC, merged